---
title: test.support.catch_unraisable_exception
permalink: /Python/test-support/catch_unraisable_exception/
date: 2021-01-01
key: Python.T.test.support.catch_unraisable_exception
category: python
tags: ['funcion python', 'test-support']
sidebar: 
  nav: python
---

## Descripción
{{site.data.Python.T.testsupport.catch_unraisable_exception.description }}

## Sintaxis
~~~python
{{ site.data.Python.T.testsupport.catch_unraisable_exception.sintaxis }}~~~

## Ejemplo
~~~python
{{ site.data.Python.T.testsupport.catch_unraisable_exception.code}}
~~~

## Artículos
<ul>
{%- for _ldc in site.data.Python.T.testsupport.catch_unraisable_exception.ldc -%}
   <li>
       <a href="{{_ldc['url'] }}">{{ _ldc['nombre'] }}</a>
   </li>
{%- endfor -%}
</ul>
